PrimeFaces.locales ['fr'] = {
    closeText: 'Fermer',
    prevText: 'Précédent',
    nextText: 'Suivant',
    monthNames: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre' ],
    monthNamesShort: ['Jan', 'Fév', 'Mar', 'Avr', 'Mai', 'Jun', 'Jul', 'Août', 'Sep', 'Oct', 'Nov', 'Déc' ],
    dayNames: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
    dayNamesShort: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    dayNamesMin: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
    weekHeader: 'Semaine',
    firstDay: 1,
    isRTL: false,
    showMonthAfterYear: false,
    yearSuffix:'',
    timeOnlyTitle: 'Choisir l\'heure',
    timeText: 'Heure',
    hourText: 'Heures',
    minuteText: 'Minutes',
    secondText: 'Secondes',
    currentText: 'Maintenant',
    ampm: false,
    month: 'Mois',
    week: 'Semaine',
    day: 'Jour',
    allDayText: 'Toute la journée',
    messages: {
        'javax.faces.component.UIInput.REQUIRED': '{0}: Erreur de validation : valeur requise.',
        'javax.faces.converter.IntegerConverter.INTEGER': '{2}: \'{0}\' doit être un nombre entier de un ou plusieurs chiffres.',
        'javax.faces.converter.IntegerConverter.INTEGER_detail': '{2}: \'{0}\' doit être un nombre entre -2147483648 et 2147483647 Exemple: {1}',
        'javax.faces.converter.DoubleConverter.DOUBLE': '{2}: \'{0}\' doit être un nombre de un ou plusieurs chiffres.',
        'javax.faces.converter.DoubleConverter.DOUBLE_detail': '{2}: \'{0}\' doit être un nombre entre 4.9E-324 et 1.7976931348623157E308  Exemple: {1}',
        'javax.faces.converter.BigDecimalConverter.DECIMAL': '{2}: \'{0}\' doit être un nombre decimal signé.',
        'javax.faces.converter.BigDecimalConverter.DECIMAL_detail': '{2}: \'{0}\' doit être un nombre decimal signé de zéro ou plusieurs chiffres, qui peut être suivit d\'un point et d\'une décimale.  Example: {1}',
        'javax.faces.converter.BigIntegerConverter.BIGINTEGER': '{2}: \'{0}\' doit être un nombre de un ou plusieurs chiffres.',
        'javax.faces.converter.BigIntegerConverter.BIGINTEGER_detail': '{2}: \'{0}\' doit être un nombre de un ou plusieurs chiffres.. Example: {1}',
        'javax.faces.converter.ByteConverter.BYTE': '{2}: \'{0}\' doit être un nombre entre 0 et 255.',
        'javax.faces.converter.ByteConverter.BYTE_detail': '{2}: \'{0}\' doit être un nombre entre 0 et 255.  Exemple: {1}',
        'javax.faces.converter.CharacterConverter.CHARACTER': '{1}: \'{0}\' doit être un caractère valide.',
        'javax.faces.converter.CharacterConverter.CHARACTER_detail': '{1}: \'{0}\' doit être un caractère ASCII valide.',
        'javax.faces.converter.ShortConverter.SHORT': '{2}: \'{0}\' doit être un nombre de un ou plusieurs chiffres.',
        'javax.faces.converter.ShortConverter.SHORT_detail': '{2}: \'{0}\' doit être un nombre entre -32768 et 32767 Exemple: {1}',
        'javax.faces.converter.BooleanConverter.BOOLEAN': '{1}: \'{0}\' doit être vrai (\'true\') où faux (\'false\')',
        'javax.faces.converter.BooleanConverter.BOOLEAN_detail': '{1}: \'{0}\' doit être vrai (\'true\') où faux (\'false\').  Tout autre valeur que \'true\' sera évaluée à \'false\'.',
        'javax.faces.validator.LongRangeValidator.MAXIMUM': '{1}: Erreur de validation: la valeur est supérieure au maximum de \'{0}\'',
        'javax.faces.validator.LongRangeValidator.MINIMUM': '{1}: Erreur de validation: la valeur est inférieure au minimum de \'{0}\'',
        'javax.faces.validator.LongRangeValidator.NOT_IN_RANGE': '{2}: Erreur de validation: l\'attribut spécifié n\'est pas entre les valeurs {0} et {1}.',
        'javax.faces.validator.LongRangeValidator.TYPE={0}': 'Erreur de validation: la validation n\'est pas du type correct.',
        'javax.faces.validator.DoubleRangeValidator.MAXIMUM': '{1}: Erreur de validation: la valeur est supérieure au maximum de \'{0}\'',
        'javax.faces.validator.DoubleRangeValidator.MINIMUM': '{1}: Erreur de validation: la valeur est inférieure au minimum de \'{0}\'',
        'javax.faces.validator.DoubleRangeValidator.NOT_IN_RANGE': '{2}: Erreur de validation: l\'attribut spécifié n\'est pas entre les valeurs {0} et {1}',
        'javax.faces.validator.DoubleRangeValidator.TYPE={0}': 'Erreur de validation: la validation n\'est pas du type correct.',
        'javax.faces.converter.FloatConverter.FLOAT': '{2}: \'{0}\' doit être un nombre entier de un ou plusieurs chiffres..',
        'javax.faces.converter.FloatConverter.FLOAT_detail': '{2}: \'{0}\' doit être un nombre entre 1.4E-45 et 3.4028235E38  Example: {1}',
        'javax.faces.converter.DateTimeConverter.DATE': '{2}: \'{0}\' ne peut être compris comme une date.',
        'javax.faces.converter.DateTimeConverter.DATE_detail': '{2}: \'{0}\' ne peut être compris comme une date. Example: {1}',
        'javax.faces.converter.DateTimeConverter.TIME': '{2}: \'{0}\' ne peut être compris comme une heure.',
        'javax.faces.converter.DateTimeConverter.TIME_detail': '{2}: \'{0}\' ne peut être compris comme une heure. Example: {1}',
        'javax.faces.converter.DateTimeConverter.DATETIME': '{2}: \'{0}\' ne peut être compris comme une date et une heure.',
        'javax.faces.converter.DateTimeConverter.DATETIME_detail': '{2}: \'{0}\' ne peut être compris comme une date et une heure. Example: {1}',
        'javax.faces.converter.DateTimeConverter.PATTERN_TYPE': '{1}: un attribut \'modèle\' où \'type\' doit être spécifié pour convertir la valeur \'{0}\'',
        'javax.faces.converter.NumberConverter.CURRENCY': '{2}: \'{0}\' ne peut être compris comme un prix.',
        'javax.faces.converter.NumberConverter.CURRENCY_detail': '{2}: \'{0}\' ne peut être compris comme un prix. Example: {1}',
        'javax.faces.converter.NumberConverter.PERCENT': '{2}: \'{0}\' ne peut être compris comme un pourcentage.',
        'javax.faces.converter.NumberConverter.PERCENT_detail': '{2}: \'{0}\' ne peut être compris comme un pourcentage. Example: {1}',
        'javax.faces.converter.NumberConverter.NUMBER': '{2}: \'{0}\' n\'est pas un nombre.',
        'javax.faces.converter.NumberConverter.NUMBER_detail': '{2}: \'{0}\' n\'est pas un nombre. Example: {1}',
        'javax.faces.converter.NumberConverter.PATTERN': '{2}: \'{0}\' n\'est pas un modèle numérique.',
        'javax.faces.converter.NumberConverter.PATTERN_detail': '{2}: \'{0}\' n\'est pas un modèle numérique. Example: {1}',
        'javax.faces.validator.LengthValidator.MINIMUM': '{1}: Erreur de validation: la longueur est inférieure au minimum de \'{0}\'',
        'javax.faces.validator.LengthValidator.MAXIMUM': '{1}: Erreur de validation: la longueur est supérieure au maximum de \'{0}\'',
        'javax.faces.validator.RegexValidator.PATTERN_NOT_SET': 'Le modèle d\'expression régulière doit être défini.',
        'javax.faces.validator.RegexValidator.PATTERN_NOT_SET_detail': 'Le modèle d\'expression régulière doit être défini à une valeur non-vide.',
        'javax.faces.validator.RegexValidator.NOT_MATCHED': 'Ne correspond pas à l\'expression régulière',
        'javax.faces.validator.RegexValidator.NOT_MATCHED_detail': 'Ne correspond pas à l\'expression régulière de \'{0}\'',
        'javax.faces.validator.RegexValidator.MATCH_EXCEPTION': 'Erreur dans l\'expression régulière.',
        'javax.faces.validator.RegexValidator.MATCH_EXCEPTION_detail': 'Erreur dans l\'expression régulière, \'{0}\''
    }

};

